language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - python --version
  - pip install -U pip
  - pip install pytest pytest-pylint
install:
  - pip install apsw retrying 'pyserial>=2.5'
  - git clone https://github.com/ppetr/persistent-queue-log.git
  - ln -s persistent-queue-log/persistent_queue.py .
  - pip freeze
script:
  - python collect.py --help
  - pytest --pylint --pylint-rcfile=pylintrc
